spring:
  application:
    name: cdebuggeandoideas-prod
  datasource:
    username: debuggeandoideas
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '20000'
    url: jdbc:postgresql://localhost:5432/companies
    password: 1234567890
